project:
  type: book
  output-dir: docs

book:
  title: "30DayMapChallenge 2023"
  author: "Soki Kimura"
  date: "11/30/2023"
  chapters:
    - index.qmd

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt

editor: visual

