project:
  type: book
  output-dir: docs

book:
  title: "30-Day Map Challenge"
  author: "Soki Kimura"
  chapters:
    - index.qmd
    - 2023.qmd
    - 2024.qmd

format:
  html:
    theme: cosmo

editor: visual

