---
title: "Day12 - South America"
author: "Soki Kimura"
date: "2023-11-13"
output: html_document
---

# Mapping Precipitation in South America

## Load libraries

```{r}

library(terra)
library(tidyterra)
library(sf)
library(tidyverse)
library(viridis)
library(showtext)

```


## Load data

```{r}

# List of South American Countries
countries <- c("AR", "BO", "BR", "CL", "CO", "EC", "FK", "GF", 
               "GY", "PY", "PE", "SR", "UY", "VE")

# Load polygons
polygon <- st_read("../Data/World_Polygons/World_Countries_Generalized/World_Countries_Generalized.shp")

# Load Precipitation data
# source: https://www.worldclim.org/data/worldclim21.html
prec <- terra::rast("../Data/World_Climate/wc2.1_5m_bio/wc2.1_5m_bio_12.tif")

```

## Extract South America Data

```{r}

# extract polygons for SA
polygon <- filter(polygon, ISO %in% countries)

# extract south america
prec_exact <- prec %>%
  terra::crop(., polygon) %>%
  terra::mask(., polygon)



```

## Create Map

```{r}

# metadata

day = 12
theme = "South America"
map_title = "Precipitation in South America"
map_subtitle = "Annual Precipitation Mapped"
sources = "WorldClim"
font = "Comic Neue"

# fonts
font= "Comic Neue"
font_add_google(font)
showtext_auto()

# plot
plot <- 
  ggplot(data = prec_exact) + 
  
  # plot
  geom_spatraster(
    data = prec_exact
  ) +
  
  labs(
    title = map_title,
    subtitle = map_subtitle,
    caption = paste("Sources:",sources, sep = " "),
    tag = paste("#30DayMapChallenge Day",day,"-",theme, sep = " "),
    color = "Category",
    x = NULL,
    y = NULL
  ) +
  
  # set legend
  scale_fill_viridis(
    option = "mako",
    begin = 1,
    end = 0.4,
    name = "Annual Precipitation",
    na.value = NA
  ) +

  theme(
    text = element_text(
      family = font,
      size = 30,
      color = "white",
      lineheight = 0.5
    ),
    plot.title = element_text(
      size = 60,
      hjust = 0,
      vjust = -2
    ),
    plot.subtitle = element_text(
      size = 40,
      hjust= 0,
      vjust = -3.5
    ),
    plot.caption = element_text(
      size = 30,
      hjust = 1
    ),
    plot.title.position = "plot",
    plot.caption.position = "plot",
    plot.tag = element_text(
      size = 30,
      hjust = 0
    ),
    plot.tag.position = c(0,1),
    plot.background = element_rect(
      fill = "gray10",
      color = NA,
    ),
    # plot.margin = margin(t = -50, r = -20, b = -20, l = -20, unit = "pt"),
    panel.background = element_blank(),
    panel.grid = element_blank(),
    axis.text = element_blank(),
    axis.ticks = element_blank(),
    legend.position = c(0.05,0.1),
    legend.justification = c("left", "bottom"),
    legend.background = element_blank(),
    legend.key = element_blank()
  )

ggsave(
  "../Maps/Day12.png",
  plot = plot,
  width = 7,
  height = 7
)



```


