---
title: "Day21 - Raster"
author: "Soki Kimura"
date: "2023-11-18"
output: html_document
---

# Mapping the Forestation

## Load libraries

```{r}

library(terra)
library(tidyterra)
library(sf)
library(tidyverse)
library(viridis)
library(showtext)
library(cowplot)
library(ggridges)
library(janitor)
source("mapping.R")

```


## Load data

```{r}

# Load polygons
polygon <- st_read("../Data/World_Polygons/World_Countries_Generalized/World_Countries_Generalized.shp")

# Load forest coverage data
# source: https://www.eorc.jaxa.jp/ALOS/en/dataset/fnf_e.htm
forest <- terra::rast("../Data/World_Climate/PSR1_10_C_025deg.tar/PSR1_10_C_025deg")

```

## Extract

```{r}

# extract polygons
forest_mask <- forest %>%
  terra::crop(., polygon) %>%
  terra::mask(., polygon) %>%
  as.numeric(.)

# make density
forest_df <- forest_mask %>%
  as.data.frame(.) %>%
  clean_names(.)

```

## Create Map

```{r}

# metadata

day = 21
theme = "raster"
map_title = "The Forest Coverage of the World"
map_subtitle = "The world mapped with the forest coverage percentage in 2010"
sources = "JAXA ALOS"

# fonts
font= "Merienda"
font_add_google(font)
showtext_auto()

# plot
p2 <- 
  ggplot(data = forest_mask) + 
  
  # plot
  geom_spatraster(
    data = forest_mask,
    show.legend = FALSE
  ) +
  
  # labels
  labs(
    title = map_title,
    subtitle = map_subtitle,
    caption = paste("Sources:",sources, sep = " "),
    tag = paste("#30DayMapChallenge Day",day,"-",theme, sep = " "),
    color = "Category",
    x = NULL,
    y = NULL
  ) +
  
  # set legend
  scale_fill_gradient(
    limits = c(0,100),
    low = "#F5F0BB",
    high = "#B3C890",
    name = "Forest Percentage",
    na.value = NA,
  ) +
  
  # set limits
  lims(
    x = c(-180, 180),
    y = c(-150, 100)
  ) +

  # set theme
  theme(
    text = element_text(
      family = font,
      size = 30,
      color = "white",
      lineheight = 0.5
    ),
    plot.title = element_text(
      size = 60,
      hjust = 0,
      vjust = -8,
      margin = margin(t = 20)
    ),
    plot.subtitle = element_text(
      size = 40,
      hjust= 0,
      vjust = -11,
      margin = margin(t = 20)
    ),
    plot.caption = element_text(
      size = 30,
      hjust = 1
    ),
    plot.title.position = "plot",
    plot.caption.position = "plot",
    plot.tag = element_text(
      size = 30,
      hjust = 0
    ),
    plot.tag.position = c(0,1),
    plot.background = element_rect(
      fill = "#73A9AD",
      color = NA,
    ),
    panel.background = element_blank(),
    panel.grid = element_blank(),
    axis.text = element_blank(),
    axis.ticks = element_blank(),
    legend.position = c(0.05,0.1),
    legend.justification = c("left", "bottom"),
    legend.background = element_blank(),
    legend.key = element_blank()
  )

# draw legend
p1 <- 
  ggplot() +
  # geom_density(
  #   aes(x = wc2.1_5m_bio_7)
  # ) + 
  
  geom_density_ridges_gradient(
    data = forest_df,
    aes(x = band_1, y = "", fill = stat(x), scale = 300),
    color = NA,
    show.legend = FALSE
  ) +
  
  coord_fixed(ratio = 1) +
  
  # set color
  scale_fill_gradient(
    name = "Forestation Percentage",
    low = "#F5F0BB",
    high = "#B3C890",
    limits = c(0,100)
  ) +
  
  # set labels
  labs(
    title = "Forestation Percentage",
    x = NULL,
    y = NULL
  ) +
  
  lims(
    x = c(0,100)
  ) +
  
  theme(
    panel.grid = element_blank(),
    panel.background = element_blank(),
    plot.background = element_blank(),
    axis.ticks = element_blank(),
    axis.text = element_text(
      family = font,
      size = 30,
      color = "white",
      lineheight = 0.5
    ),
    text = element_text(
      family = font,
      size = 30,
      color = "white",
      lineheight = 0.5
    )
  )

# combine plots
plot <- 
  ggdraw() +
  draw_plot(p2) +
  draw_plot(p1, x = 0, y = 0, width = 0.5, height = 0.3)

ggsave(
  "../Maps/Day21.png",
  plot = plot,
  width = 7,
  height = 7
)



```



