---
title: "Day13_Chloropleth"
author: "Soki Kimura"
date: "2023-11-13"
output: html_document
---

# Left to do

- Do something with the labels
- Do something with the legend
- Change colors of choropleth

# Load data

```{r}

library(sf)
library(dplyr)
library(tidyverse)
library(readr)
library(showtext)
library(tmap)
library(tmaptools)

source("mapping.R")

font_add_google("Fira Sans")
font_add_google("Hammersmith One")
showtext_auto()

# load London Boroughs
boroughs <- st_read("../Data/London_polygons/London_Boroughs.gpkg") %>%
  st_transform(., 27700)

# load River Thames
thames <- st_read("../Data/London_polygons/River_Thames_simplified.gpkg") %>%
  st_transform(., 27700)

# load fire data
# source https://data.london.gov.uk/dataset/lfb-fires-in-london-1966-2019---fire-facts
fires <- read_csv("../Data/Fire/Fires_by_Borough.csv") %>%
  select(., "Borough", "2022") %>%
  rename(., fire = "2022")
```

# join data

```{r}

borough_fire <- boroughs %>%
  left_join(., fires,
            by = c("name" = "Borough")) %>%
  mutate(., fire_per_km2 = fire / hectares * 100)

```

# map data

```{r}


box <- st_bbox(borough_fire) %>%
  square_bbox(., 1.1) %>%
  move_bbox(., 0, 0.05)

day = 13
theme = "Choropleth"
map_title = expression("Fires in London Boroughs in 2022 per km"^2)
sources = "OpenStreetMap, London Data Store"

exp_line1 = expression("Number of Fires in 2022 in Each Borough per km"^2)
exp_line2 = ""

tmap_mode("plot")

map <- 
  tm_shape(borough_fire, bbox = box) +
    tm_polygons(col = "fire_per_km2",
                border.col = "white",
                border.lwd = 3,
                title = expression("Fires per km"^2)) + 
    tm_text("name",
            size = 1,
            col = "gray20") +
  tm_shape(thames) +
    tm_fill(col = "white") +
      tm_credits(exp_line1,
             col = "gray40",
             size = 3,
             position = c(0,0.78),
             just = 0) +
  tm_credits(exp_line2,
             col = "gray40",
             size = 3,
             position = c(0,0.74),
             just = 0) +
  tm_credits(paste("#30DayMapChallenge Day ", day, " - ",theme),
             col = "gray40",
             size = 2,
             position = c(0,1),
             just = c(0,1)) +
  tm_compass(type="8star",
             show.labels = FALSE,
             color.dark = "gray40",
             size = 6,
             position = c(0,0.07),) +
  tm_credits(paste("Sources:", sources, sep = " "), 
             col = "gray40",
             size = 2,
             position = c(0,0)) + 
  tm_layout(bg.color = "white",
            scale = 1,
            frame = FALSE,
            fontfamily = "Fira Sans",
            title = map_title,
            title.color = "gray20",
            title.size = 5,
            title.position = c(0.02,0.90),
            legend.position = c(1,0.1),
            legend.just = c(1,0),
            legend.title.size = 3,
            legend.text.size = 1.5,
            legend.height = 1,
            )

tmap_save(map,filename = "../Maps/Day13.png")
    
  
```


